modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="cursedmod"
version="1.0.0"
displayName="Cursed Mod"
description='''
Проклятый мод - чем больше умираешь, тем страшнее!
Убей дракона чтобы снять проклятие!
'''

[[dependencies.cursedmod]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="CLIENT"

[[dependencies.cursedmod]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="CLIENT"